apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-prcz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-prcz
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-prcz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-prcz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-prcz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-sgff-tenant/status-quarkus-io/statusquarkusio-prcz@sha256:dd8f81e772864b8f3d1164eaec5f6fcf97bdfce94e96723b86bd7f36bfaed957
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
