apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-prcz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-sgff-tenant/status-quarkus-io/statusquarkusio-prcz@sha256:dd8f81e772864b8f3d1164eaec5f6fcf97bdfce94e96723b86bd7f36bfaed957
        name: my-java-quarkus
        resources: {}
status: {}
